n1 = input('1st number: ')
n2 = input('2nd number: ')
n1 = int(n1)
n2 = int(n2)

print(f"Sum: {n1+n2}")
print(f"Difference: {n1-n2}")
print(f"Product: {n1*n2}")
print(f"Power: {n1**n2}")
print(f"Quotient (int): {n1//n2}")
print(f"Quotient (float): {n1/n2}")
print(f"Remainder: {n1%n2}")